Feature: Add Master Master replication
Deveryware/ansible-role-mysql pull request #2
Opened 2020-11-19 08:05 UTC by OliPou

2020-11-20 12:52 UTC, olo-dw commented
Thank you for your contribution.

2020-11-23 14:10 UTC, Aversiste requested changes

2020-11-23 14:10 UTC, Aversiste commented on README.md
> +## Replication Master Master
There are no sections dedicated to the Master/Slave replication mode so for consistency there should be either no section for Master/Master or an equivalent section for Master/Slave.

2020-11-23 14:10 UTC, Aversiste commented on README.md
> +## Replication Master Master
Plus the order of words in the title is wrong: `Master Master Replication` seems better.

2020-11-23 14:10 UTC, Aversiste commented on README.md
> +        - { role: ansible-role-mysql, mysql_replication_master_master: true}
Booleans are not necessarily the best idea, I would prefer `mysql_replication_mode: comaster|masterslave` for example. It is easier if other methods are added later and reduce the overall number of variables.

2020-11-23 14:10 UTC, Aversiste commented on README.md
> +    mysql_server_id:
Is this an example ? Why is only one variable assigned some values ? What does this value mean ?

2020-11-23 14:10 UTC, Aversiste commented on tasks/replication-master-master.yml
> +    - (mysql_replication_role == 'master01') or (mysql_replication_role == 'master02')
Doesn't look good.

2020-11-23 14:10 UTC, Aversiste commented on tasks/replication-master-master.yml
> +- name: Stop slave if error replication status is detected.
```suggestion
- name: Stop slave if replication status is in error.
```

2020-11-23 14:10 UTC, Aversiste commented on tasks/replication-master-master.yml
> +  mysql_replication: mode=getmaster
This is not consistent with previous instances of `mysql_replication`.
```suggestion
  mysql_replication:
    mode: getmaster
```

2020-11-23 14:10 UTC, Aversiste commented on tasks/replication-master-master.yml
> +  mysql_replication: mode=startslave
Same thing here.

2020-11-23 14:10 UTC, Aversiste commented on tasks/replication-master-master.yml
> +- name: Generate error when slave status is failed
```suggestion
- name: Generate an error if slave status is failed
```

2020-12-14 08:08 UTC, closed without merging

2020-12-14 08:08 UTC, OliPou commented
I'll pull a new request with my new code